image: gtf-system-registry.ap-southeast-5.cr.aliyuncs.com/gopay-systems/cx-java:jdk-21
include:
- local: /_deployments/gitlab/integration.yml
variables:
    GOPAYSH_IMAGE: asia.gcr.io/your-image-registry/pacman-bot:${CI_COMMIT_SHORT_SHA}
stages:
  - artefact-build
  - deploy

