image: gtf-system-registry.ap-southeast-5.cr.aliyuncs.com/gopay-systems/cx-java:jdk-11
include:
- local: /_deployments/gitlab/integration.yml
variables:
    GOPAYSH_IMAGE: gtf-system-registry.ap-southeast-5.cr.aliyuncs.com/gopay-systems/pacman-bot:${CI_COMMIT_SHORT_SHA}
stages:
  - artefact-build
  - deploy

